no_h=50;
net = feedforwardnet(no_h,'traingdx');
net = configure(net,x,t);
rand('seed',1997);
IW = 1*(rand(no_h,in_dim)-0.5);
b1 = 1*(rand(no_h,1)-0.5);
LW = 1*(rand(out_dim,no_h)-0.5);
b2 = 1*(rand(out_dim,1)-0.5);
net.IW{1,1} = IW;
net.b{1,1} = b1;
net.LW{2,1} = LW;
net.b{2,1} = b2;
net.layers{1}.transferFcn = 'tansig';
net.layers{2}.transferFcn ='tansig';
view(net);